### ISSUE TITLE
add redeem nft button somewhere 

### ISSUE THREAD

**Issue by davidwang98** [ong6/amuze#25]
(if still ongoing can just put tour still running, maybe adi can create a get function for frontend)

**Comment by ong6** [comment]
wtf does this do

**Comment by davidwang98** [comment]
unless the nft automatically goes into your wallet upon ending the tour, need to redeem

**Comment by davidwang98** [comment]
@AdithyaNarayan can advise pls

**Comment by ong6** [comment]
isnt that redeem rewards

**Comment by AdithyaNarayan** [comment]
Redeem rewards and redeem nft is diff

Redeem rewards can happen anytime

Redeem nft can only be called by original owner after time lock to get back nft
